# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notification_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1anotification_service.proto\x12\x14notification_service\"`\n\x12SendMessageRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x37\n\x0cmessage_type\x18\x02 \x01(\x0e\x32!.notification_service.MessageType\"7\n\x13SendMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"+\n\x16GetClientStatusRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\xac\x01\n\x17GetClientStatusResponse\x12Z\n\x0f\x63lient_statuses\x18\x01 \x03(\x0b\x32\x41.notification_service.GetClientStatusResponse.ClientStatusesEntry\x1a\x35\n\x13\x43lientStatusesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*2\n\x0bMessageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05HELLO\x10\x01\x12\x0b\n\x07GOODBYE\x10\x02\x32\xe9\x01\n\x13NotificationService\x12\x62\n\x0bSendMessage\x12(.notification_service.SendMessageRequest\x1a).notification_service.SendMessageResponse\x12n\n\x0fGetClientStatus\x12,.notification_service.GetClientStatusRequest\x1a-.notification_service.GetClientStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCLIENTSTATUSRESPONSE_CLIENTSTATUSESENTRY']._loaded_options = None
  _globals['_GETCLIENTSTATUSRESPONSE_CLIENTSTATUSESENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGETYPE']._serialized_start=427
  _globals['_MESSAGETYPE']._serialized_end=477
  _globals['_SENDMESSAGEREQUEST']._serialized_start=52
  _globals['_SENDMESSAGEREQUEST']._serialized_end=148
  _globals['_SENDMESSAGERESPONSE']._serialized_start=150
  _globals['_SENDMESSAGERESPONSE']._serialized_end=205
  _globals['_GETCLIENTSTATUSREQUEST']._serialized_start=207
  _globals['_GETCLIENTSTATUSREQUEST']._serialized_end=250
  _globals['_GETCLIENTSTATUSRESPONSE']._serialized_start=253
  _globals['_GETCLIENTSTATUSRESPONSE']._serialized_end=425
  _globals['_GETCLIENTSTATUSRESPONSE_CLIENTSTATUSESENTRY']._serialized_start=372
  _globals['_GETCLIENTSTATUSRESPONSE_CLIENTSTATUSESENTRY']._serialized_end=425
  _globals['_NOTIFICATIONSERVICE']._serialized_start=480
  _globals['_NOTIFICATIONSERVICE']._serialized_end=713
# @@protoc_insertion_point(module_scope)
